# Default values for acg-inventory-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
baseDomain: sample.com

aws:
  region: us-east-1
  accountId: 12345678909
  
image:
  repository: 
    name: bookstore.inventory-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  containerPort: 5001
  name: inventory-api-service
  scheme: internet-facing
  servicePort: 80


resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
