---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: {{ template "acg-front-end.name" . }}-proxy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "acg-front-end.name" . }}-proxy
      release: {{ .Release.Name }}
  listeners:
    - portMapping:
        port: {{ .Values.service.containerPort }}
        protocol: http
  serviceDiscovery:
    dns:
      hostname: {{ .Values.service.name }}
  logging:
    accessLog:
      file:
        path: "/dev/stdout"
        format:
          text: string
  backends:
    - virtualService:
        virtualServiceRef:
          name: resource-api-service
    - virtualService:
        virtualServiceRef:
          name: clients-api-service
    - virtualService:
        virtualServiceRef:
          name: inventory-api-service
    - virtualService:
        virtualServiceRef:
          name: renting-api-service

---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: {{ .Values.service.name }}-proxy
  namespace: {{ .Release.Namespace }}
spec:
  awsName: {{ .Values.service.name }}
  provider:
    virtualRouter:
      virtualRouterRef:
        name: {{ template "acg-front-end.name" . }}-proxy-virtual-router

--- 
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: {{ template "acg-front-end.name" . }}-proxy-virtual-router
  namespace: {{ .Release.Namespace }}
spec:
  listeners:
    - portMapping:
        port: {{ .Values.service.containerPort }}
        protocol: http
  routes:
    - name: {{ template "acg-front-end.name" . }}-proxy-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: {{ template "acg-front-end.name" . }}-proxy
              weight: 1
        retryPolicy:
          maxRetries: 10
          perRetryTimeout:
            unit: ms
            value: 2000
          httpRetryEvents:
            - server-error
            - gateway-error