apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata: 
  name: {{ .Values.az1.name }}
spec: 
  securityGroups: 
    - {{ .Values.az1.sg1 }}
    - {{ .Values.az1.sg2 }}
  subnet: {{ .Values.az1.subnetId }}