apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata: 
  name: {{ .Values.az3.name }}
spec: 
  securityGroups: 
    - {{ .Values.az3.sg1 }}
    - {{ .Values.az3.sg2 }}
  subnet: {{ .Values.az3.subnetId }}